routes/admin.php
<?php

use App\Http\Controllers\Admin\PonenteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PagoController;
use App\Http\Controllers\Admin\EventoController;
use App\Http\Controllers\Admin\ReferenciaController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SubcategoriaController;
use App\Http\Controllers\Admin\PermisoController;
use App\Http\Controllers\Admin\PatrocinadorController;

Route::get('', [HomeController::class, 'index'])->middleware('can:admin.home')->name('admin.home');
Route::resource('users', UserController::class)->only(['index','edit','update','destroy'])->names('admin.users');
Route::resource('roles', RoleController::class)->names('admin.roles');
Route::resource('permisos', PermisoController::class)->names('admin.permisos');
Route::resource('categorias',CategoriaController::class)->names('admin.categorias');
Route::resource('pagos',PagoController::class)->names('admin.pagos');
Route::get('pagos/aprobarpago/{pago}', [PagoController::class, 'aprobarpago'])->name('admin.pagos.aprobarpago');
Route::get('pagos/declinarpago/{pago}', [PagoController::class, 'declinarpago'])->name('admin.pagos.declinarpago');
Route::resource('eventos',EventoController::class)->names('admin.eventos');
Route::get('eventos/asistencia/{evento}', [EventoController::class, 'asistencia'])->name('admin.eventos.asistencia');
Route::get('eventos/lista/{evento}', [EventoController::class, 'lista'])->name('admin.eventos.lista');
Route::get('/admin/eventos/{id}/eventopago', [EventoController::class, 'eventopago'])->name('admin.eventos.eventopago');
Route::resource('participantes', 'App\Http\Controllers\Admin\ParticipanteController')->names('admin.participantes');
Route::resource('referencias',ReferenciaController::class)->names('admin.referencias');
Route::resource('subcategorias',SubcategoriaController::class)->names('admin.subcategorias');
Route::get('subcategorias/listarsubcategorias/',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::resource('patrocinadores',PatrocinadorController::class)->names('admin.patrocinadores');
Route::resource('ponentes',PonenteController::class)->names('admin.ponentes');
//Route::post('subcategorias/listarsubcategorias',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::get('users/export/{evento_id}', [UserController::class, 'export'])->name('admin.user.export');

routes/user.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ParticipanteController;
use App\Http\Controllers\User\EventoController;
use App\Http\Controllers\User\PagoController;

Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::resource('participante', ParticipanteController::class)->names('user.participantes');
Route::resource('evento', EventoController::class)->names('user.eventos');
Route::resource('pago', PagoController::class)->names('user.pagos');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventoController;
use App\Http\Controllers\ParticipanteController;

Route::get('/', [EventoController::class,'index'])->name('eventos.index');
Route::get('Eventos/{evento}', [EventoController::class,'show'])->name('eventos.show');
Route::get('/premiacion', function () {
    return view ('premiacion');
})->name('premiacion');



Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Http/Livewire/Admin/Asistencia.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\User;
use App\Models\Evento;

class Asistencia extends Component
{
    protected $listeners = ['asistenciaP'];
    public $nombreP;
    //public $decodedText;
    public function render()
    {
       //$idParticipante = $this->decodedText;
        return view('livewire.admin.asistencia');
    }
    public function asistenciaP($eventoinf)
    {
       $evento = Evento::with('pagos')->find($eventoinf[1])->all();
       //dd($evento); 
       $existe= array_search($eventoinf[0],$evento);
       dd($existe);
       $this->nombreP= $eventoinf;
        
    }
}

app/Http/Livewire/Admin/CategoriaSubcategoria.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Categoria;
use App\Models\Subcategoria;

class CategoriaSubcategoria extends Component
{
    public $categorias;
    public $categoriaId;
    public $wsubcategorias;
    public $wsubcategoriasId;
    public function mount(){
        $this->categorias = Categoria::orderby('nombre')->get();
    }
    public function updatedCategoriaId(){
        
        //$this->wsubcategorias="uno";
        if($this->categoriaId !=''){
            $this->wsubcategorias = Categoria::find($this->categoriaId)->subcategorias;
        }else{
            $data= array("id" => "No","nombre"=> "hay datos");
            $this->wsubcategorias =json_encode($data);
        }
    }
    public function render()
    {
        return view('livewire.admin.categoria-subcategoria');
    }
    public function mostrarSubcategorias(){
       $wiresubcategorias="hola";
        //$subcategorias= Categoria::find($categoria)->subcategoria->get();
    }
}

app/Http/Livewire/Admin/CreateEvento.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class CreateEvento extends Component
{
    public function render()
    {
        return view('livewire.admin.create-evento');
    }
}

app/Http/Livewire/Admin/EventoIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Evento;
use Livewire\WithPagination;

class EventoIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;  //vincula la barra de busqueda en la vista
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
        $eventos = Evento::with('pagos','setevento')->where('nombre','LIKE' ,'%'.$this->search.'%')
        ->latest('id')
        ->paginate(10);
        return view('livewire.admin.evento-index', compact('eventos'));
    }
}

app/Http/Livewire/Admin/PagosEvento.php
<?php

namespace App\Http\Livewire\Admin;

use App\Exports\UsersPagosExport;
use App\Exports\UsersAsistenciaExport;
use Livewire\Component;
use App\Models\Evento;
use App\Models\Pago;
use Illuminate\Database\Eloquent\Collection;
use Livewire\WithPagination;

class PagosEvento extends Component
{
    use WithPagination;
    public Collection $pagosexport;
    public $selectEvento= null;
    public $pagos = null;
    public $evento = null;
   // public $pagose;
    
    //ESTO DA LOS VALORES PARA EL SELECT
    public function updatedselectEvento($evento_id)
    {
       if($evento_id != "vacio"){
        $this->pagos = Pago::select('pagos.id','users.name','users.pname','users.mname','users.email','participantes.celular','participantes.numero','pagos.referencia','pagos.monto','participantes.talla','participantes.modalidad','participantes.tiposanguineo','participantes.emergencia','participantes.responsabilidad','pagos.estatuspago')
        ->join ('participantes', 'participantes.id', '=','pagos.participante_id')
        ->join ('users','users.id', '=','participantes.id')
        ->join('evento_pago','evento_pago.pago_id','=','pagos.id')
        ->where('evento_pago.evento_id','=',$evento_id)
        ->get();
        
       }else{
        $this->reset('evento','pagos');
       }
    }
    
    public function render()
    {
        $eventos= Evento::with('participantes:id,talla')->where('status',2)
        ->orderBy('id', 'DESC')
        ->get(['id','nombre']);
        return view('livewire.admin.pagos-evento',compact('eventos'));
    }
    public function exportPagos(){
        return (new UsersPagosExport($this->selectEvento))->download('Pagos.xlsx');
    }
    public function exportAsistencia(){
        return (new UsersAsistenciaExport($this->selectEvento))->download('ListaAsistencia.xlsx');
    }
}

app/Http/Livewire/Admin/PatrocinadoresIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Patrocinador;
use Livewire\WithPagination;

class PatrocinadoresIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;  //vincula la barra de busqueda en la vista
    protected $listeners=['render'=>'render'];
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
        $patrocinadores = Patrocinador::with('image')
        ->where('nombre','LIKE' ,'%'.$this->search.'%')
        ->latest('id')
        ->paginate(10);
        return view('livewire.admin.patrocinadores-index', compact('patrocinadores'));
        //return view('livewire.admin.patrocinadores-index');
    }
}

app/Http/Livewire/Admin/PermisosIndex.php
<?php

namespace App\Http\Livewire\Admin;
use Spatie\Permission\Models\Permission;
use Livewire\WithPagination;

use Livewire\Component;

class PermisosIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;  //vincula la barra de busqueda en la vista
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
    $permisos = Permission::where('name','LIKE' ,'%'.$this->search.'%')
    ->orWhere('description', 'like','%'.$this->search .'%')
    ->latest('id')
    ->paginate(10);
        return view('livewire.admin.permisos-index',compact('permisos'));
    }
}

app/Http/Livewire/Admin/PonentesIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Ponente;
use Livewire\Component;
use Livewire\WithPagination;

class PonentesIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;  //vincula la barra de busqueda en la vista
    protected $listeners=['render'=>'render'];
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
        
        $ponentes = Ponente::with('image')
        ->where('nombre','LIKE' ,'%'.$this->search.'%')
        ->latest('id')
        ->paginate(10);
        //dd($ponentes);
        return view('livewire.admin.ponentes-index', compact('ponentes'));
        //return view('livewire.admin.patrocinadores-index');
       
    }
}

app/Http/Livewire/Admin/ReferenciaIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Referencia;

class ReferenciaIndex extends Component
{
    public $search;
    public function render()
    {
        $referencias = Referencia::where('tipo', 'like','%'.$this->search .'%')
        ->orWhere('tipo', 'like','%'.$this->search .'%')
        ->latest('id')
        ->paginate(10);
        return view('livewire.admin.referencia-index',compact('referencias'));
    }
}

app/Http/Livewire/Admin/Subcategorias.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Subcategoria;
use Livewire\Component;
use Livewire\WithPagination;
class Subcategorias extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    public $search;  //vincula la barra de busqueda en la vista
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
        $subcategorias = Subcategoria::where('nombre','LIKE' ,'%'.$this->search.'%')
        ->latest('id')
        ->paginate(10);
        return view('livewire.admin.subcategorias', compact('subcategorias'));
        
    }
}

app/Http/Livewire/Admin/UsersIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\User;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;
    public $search;

    protected $paginationTheme = "bootstrap";
    
    public function updatingSearch(){ //sirve para resetear la paginacion de la tabla
        $this->resetPage();

    }
    public function render()
    {
        $users = User::where('name','LIKE','%' .$this->search. '%')
        ->orWhere('email','LIKE','%' .$this->search. '%')
        ->paginate();
        
        return view('livewire.admin.users-index', compact('users'));
    }
}

app/Http/Livewire/Aside.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Aside extends Component
{
    public function render()
    {
        return view('livewire.aside');
    }
}

app/Http/Livewire/Footer.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Footer extends Component
{
    public function render()
    {
        return view('livewire.footer');
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Categoria;


class Navigation extends Component
{
    public function render()
    {
        $categorias = Categoria::all();
        return view('livewire.navigation', compact('categorias'));
    }
}

app/Http/Livewire/User/DatosPago.php
<?php

namespace App\Http\Livewire\User;

use App\Models\Pago;
use App\Models\Evento;
use App\Models\Participante;
use App\Models\Tipoparticipante;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class DatosPago extends Component
{
    public $evento;
    public function render()
    {
       
        $participante = Participante::find(Auth()->user()->id);       
        $evento = $this->evento;
        if(!$referencia= $participante->subcategorias()->get()){
           $referencia="free"; 
        }
        //dump($referencia);
        return view('livewire.user.datos-pago',compact('referencia','evento'));
    }
}

app/Http/Livewire/User/DatosParticipante.php
<?php

namespace App\Http\Livewire\User;

use App\Models\Participante;
use App\Models\Referencia;
use Livewire\Component;
use App\Models\Evento;
use \App\Models\User;
use \App\Models\Subcategoria;
class DatosParticipante extends Component
{
    public $evento;
    public $club;
    public $existe;
    public $test= false;
    public function render()
    {
        $participante = Participante::find(auth()->user()->id);
        $even =$this->evento;
        $existe = $even->participantes()->find($participante->id);
        //$evento = $even->referencias()->get();
        $subcategorias= $even->subcategorias()->get();
        //dd($subcategorias);
        return view('livewire.user.datos-participante', compact('participante','subcategorias','existe'));

    }
    public function updatedClub()
    {
      return $this->club;
    }
}

app/Http/Livewire/User/EventoIndex.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;
use App\Models\Evento;
use App\Models\Participante;
use Illuminate\Support\Facades\Auth;
use Livewire\WithPagination;
use App\Models\Pago;
use Carbon\Carbon;

class EventoIndex extends Component
{
    use WithPagination;
    protected $paginationTheme = "bootstrap";
    //public $hoy = Carbon::now()->format(Y-m-d);
    public function render()
    {
        $hoy = Carbon::now()->format('Y-m-d');
        
        // Número de eventos por página
        $porPagina = 9; // Ajusta este número según tus necesidades
        
        /*$eventos = Evento::select('eventos.*') // Selecciona todas las columnas de la tabla eventos
            ->join('Seteventos', 'eventos.id', '=', 'Seteventos.evento_id') // Asegúrate de que la clave foránea es correcta
            ->where('eventos.status', 2)
            ->where(function ($query) use ($hoy) {
                $query->whereBetween($hoy, ['Seteventos.iniciainscripcion', 'Seteventos.terminainscripcion'])
                      ->orWhere('Seteventos.fechaevento', '>=',$hoy);
            })
            ->orderBy('Seteventos.fechaevento', 'asc') // Ordenar por fecha del evento en orden ascendente
            ->paginate($porPagina)
            ->withQueryString(); 
        */
        $eventos = Evento::with(['Setevento','participantes:id','pagos:id,estatuspago,participante_id','image','categoria'])
        ->where('status',2)
        ->latest('id')
        ->paginate(9);
        return view('livewire.user.evento-index', compact('eventos'));
        
    }
}

app/Http/Livewire/User/MisPago.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class MisPago extends Component
{
    public function render()
    {
        return view('livewire.user.mis-pago');
    }
}

resources/views/livewire/admin/asistencia.blade.php
<div class="card">
        <div class="card-body">
            <div id="qr-reader" style="width:350px"></div>
            <div id="qr-reader-results"></div>
        </div> 
</div>

resources/views/livewire/admin/evento-index.blade.php
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <input wire:model="search" class="form-control" type="text" placeholder="Ingrese el nombre del evento que desea encontrar">
            </div>
        </div>
    </div>
    
    @if ($eventos->count())
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-left">Nombre</th>
                    <th class="text-center">Capacidad</th>
                    <th class="text-center">Inscritos</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center"> Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($eventos as $evento)
                    <tr>
                        <td class="align-middle">{{$evento->nombre}}</td>
                        <td class="align-middle text-center">{{$evento->setevento->capacidad}}</td>
                        <td class="align-middle text-center">
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width:{{($evento->setevento->inscritos/$evento->setevento->capacidad)*100}}%;" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100">{{($evento->setevento->inscritos/$evento->setevento->capacidad)*100}}% -- {{$evento->setevento->inscritos}}</div>
                            </div>
                              
                        </td>
                        <td class="align-middle text-center">
                            @if($evento->status==2)
                                <span class="badge badge-success">Publicado</span> 
                            @else 
                                <span class="badge badge-warning">Borrador</span>                              
                            @endif
                        </td>
                        <!--td>                    
                            <a href="{{route('admin.eventos.lista',$evento)}}"><i class="fas fa-solid fa-users"></i></a>
                        </td-->
                        <td class="vertical-alignment d-flex flex-column">
                            <a class="btn btn-outline-info btn-sm mb-1 d-flex align-items-center justify-content-center" href="{{route('admin.eventos.asistencia',$evento)}}"><i class="fas fa-list"></i></a>
                            <a class="btn btn-outline-info btn-sm mb-1 d-flex align-items-center justify-content-center" href="{{route('admin.eventos.show',$evento)}}"><i class="fas fa-eye"></i></a>
                            <a class="btn btn-outline-primary btn-sm mb-1 d-flex align-items-center justify-content-center" href="{{route('admin.eventos.edit',$evento)}}"><i class="fas fa-edit"></i></a>
                            <form class="form-inline d-flex flex-column mb-1" action="{{route('admin.eventos.destroy',$evento)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-outline-danger btn-sm d-flex align-items-center justify-content-center" style="width: 100%; height: 100%;"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </td>                  
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="card footer">
        {{$eventos->links()}}
    </div>      
    @else
    <div class="card-body">
        <strong>No hay registros</strong>
    </div>
    @endif
</div>

resources/views/livewire/admin/patrocinadores-index.blade.php
<div>
<x-adminlte-card theme="lime" theme-mode="outline">
    <div class="card-header">
        <div class="row">
           
            <div class="col-md-11">
                <input wire:model="search" class="form-control" type="text" placeholder="Ingrese el nombre del patrocinador">
            </div>
            <div class="col-md-1">
                <a type="button" class="btn btn-primary btn-md" href="{{route('admin.patrocinadores.create')}}">Nuevo</a>
          </div>
        </div> 
    </div>
   
    @if($patrocinadores->count())
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Logo</th>
                    <th>Description</th>
                    <th>web</th>
                    <th>Redes</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($patrocinadores as $patrocinador)
                <tr>
                 
                    <td>{{$patrocinador->nombre}}</td>
                    <td><img class="img img-rounded"  src="@if($patrocinador->image){{Storage::url($patrocinador->image->url)}} @else {{Storage::url('patrocinadores/empty.png')}} @endif " width="50px" height="50px"/> </td>
                    <td>{{$patrocinador->descripcion}}</td>
                    <td>{{$patrocinador->pagina_web}}</td>
                    <td>
                        @foreach (json_decode($patrocinador->redes) as $item =>$key)
                            <h6 class="text-small">{{$item}}:<small>{{$key}} </small></h6>
                        @endforeach    
                    </td>
                    <td with="10px"> 
                        <a class="btn btn-outline-primary btn-sm" href="{{route('admin.patrocinadores.edit', $patrocinador)}}"><i class="fas fa-sm fa-pen"></i></a>
                    </td>
                                    <td with="10px">
                                        <form action="{{route('admin.patrocinadores.destroy',$patrocinador)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <x-adminlte-button class="btn-sm" type="submit" theme="outline-danger" icon="fas fa-sm fa-trash"/>
                                        </form>
                                    </td> 
                </tr>
                @endforeach
            </tbody> 
            <tfoot>
              
            </tfoot>             
            @else
            <div class="card-body">
                <strong>No hay registros</strong>
            </div>
            @endif
             
        </table>
        {{$patrocinadores->links()}}
    </div>
   
</x-adminlte-card>
@section('js')
<script>
window.addEventListener('show-modal', (order) => {
   
    $('#patrocinadormodal').modal(order);
    //console.log(order.detail.order);
    if(order.detail.order == 'hidden'){
        //console.log('entra');
    $('.modal-backdrop').removeClass('show');
        //$(document.body).removeClass("modal-open");
   // $('.ruben').modal(order);
    }
    
})
</script>
@endsection
</div>

resources/views/livewire/admin/ponentes-index.blade.php
<div>
    <x-adminlte-card theme="lime" theme-mode="outline">
        <div class="card-header">
            <div class="row">
                <div class="col-md-11">
                    <input wire:model="search" class="form-control" type="text" placeholder="Ingrese el nombre del patrocinador">
                </div>
                <div class="col-md-1">
                    <a type="button" class="btn btn-primary btn-md" href="{{route('admin.ponentes.create')}}">Nuevo</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @if ($ponentes->count())
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Nivel Educativo</th>
                        <th>Puesto</th>
                        <th>Compañia</th>
                        <th>Ponencia</th>
                        <th>Foto</th>
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
              
                <tbody>
                    @foreach ($ponentes as $ponente)
                        <tr>
                            <td>{{$ponente->nombre}}</td>
                            <td>{{$ponente->nivestudio}}</td>
                            <td>{{$ponente->puesto}}</td>
                            <td>{{$ponente->compania}}</td>
                            <td>{{$ponente->ponencia}}</td>
                            <td><img class="img img-rounded"  src="@if($ponente->image){{Storage::url($ponente->image->url)}} @else {{Storage::url('ponentes/empty.png')}} @endif" width="50px" height="50px" /> </td>
                            <td with="10px">
                                <a class="btn btn-outline-primary btn-sm" href="{{route('admin.ponentes.edit', $ponente)}}"><i class="fas fa-sm fa-pen"></i></a>
                                
                            <td with="10px">
                                <form action="{{route('admin.ponentes.destroy',$ponente)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <x-adminlte-button class="btn-sm" type="submit" theme="outline-danger" icon="fas fa-sm fa-trash"/>
                                </form>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>

                </tfoot>
            </table>
              @else
                  <p>No hay registros</p>
              @endif
            
        </div>
    </x-adminlte-card>
</div>

resources/views/livewire/admin/subcategorias.blade.php
<div class="card-header">
    <div class="row">
        <div class="col-md-11">
            <input wire:model="search" class="form-control" type="text" placeholder="Ingrese el nombre de la subcategoria">
        </div>
        <div class="col-md-1">
            <a href="{{route('admin.subcategorias.create')}}" class="btn btn-sm btn-outline-info">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
            </a>
        </div>
    </div>

@if ($subcategorias->count())
<table class="table table-stripped table-condensed">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Referencia</th>
            <th>Precio</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
    @foreach ($subcategorias as $subcat)
        <tr>
            <td>
                {{$subcat->nombre}}
            </td>
            <td>
                {{$subcat->referencia}}
            </td>
            <td>
                ${{$subcat->precio}}.00
            </td> 
            <td with="10px">
                <a class="btn btn-outline-primary btn-sm" href="{{route('admin.subcategorias.edit',$subcat)}}">Editar</a>
            </td>
            <td with="10px">
                <form action="{{route('admin.subcategorias.destroy',$subcat)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-outline-danger btn-sm">Eliminar</button>
                </form>
            </td>                     
        </tr>
    @endforeach
    </tbody>
</table>
<div class="card footer">
    {{$subcategorias->links()}}
</div>
@else
<div class="card-body">
    <strong>No hay registros</strong>
</div>
@endif
</div> 

resources/views/livewire/admin/tipoparticipante-index.blade.php
<div>
    <div class="card">
        <div class="card-body">
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                referencia
            </th>
            <th>
                tipo
            </th>
            <th>
                monto:
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach ($tipo as $tipo)
        <tr>
        <td>
        {{$tipo->referencia}}
        </td> 
        <td>
            {{$tipo->tipo}}
        </td>
        <td>
            ${{$tipo->precio}}.00
        </td>
        <td with="10px">
            <a class="btn btn-outline-primary btn-sm" href="{{route('admin.tipoparticipante.edit', $tipo)}}">Editar</a>
        </td>
        <td with="10px">
            <form action="{{route('admin.tipoparticipante.destroy',$tipo)}}" method="POST">
                @csrf
                @method('DELETE')
                <button class="btn btn-outline-danger btn-sm">Eliminar</button>
            </form>
        </td>
        </tr>        
        @endforeach

    </tbody>

</table>
            @foreach ($tipo as $tipo)
                
            @endforeach

        </div>
    </div>
</div>