routes/admin.php
<?php

use App\Http\Controllers\Admin\PonenteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PagoController;
use App\Http\Controllers\Admin\EventoController;
use App\Http\Controllers\Admin\ReferenciaController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SubcategoriaController;
use App\Http\Controllers\Admin\PermisoController;
use App\Http\Controllers\Admin\PatrocinadorController;

Route::get('', [HomeController::class, 'index'])->middleware('can:admin.home')->name('admin.home');
Route::resource('users', UserController::class)->only(['index','edit','update','destroy'])->names('admin.users');
Route::resource('roles', RoleController::class)->names('admin.roles');
Route::resource('permisos', PermisoController::class)->names('admin.permisos');
Route::resource('categorias',CategoriaController::class)->names('admin.categorias');
Route::resource('pagos',PagoController::class)->names('admin.pagos');
Route::get('pagos/aprobarpago/{pago}', [PagoController::class, 'aprobarpago'])->name('admin.pagos.aprobarpago');
Route::get('pagos/declinarpago/{pago}', [PagoController::class, 'declinarpago'])->name('admin.pagos.declinarpago');
Route::resource('eventos',EventoController::class)->names('admin.eventos');
Route::get('eventos/asistencia/{evento}', [EventoController::class, 'asistencia'])->name('admin.eventos.asistencia');
Route::get('eventos/lista/{evento}', [EventoController::class, 'lista'])->name('admin.eventos.lista');
Route::get('/admin/eventos/{id}/eventopago', [EventoController::class, 'eventopago'])->name('admin.eventos.eventopago');
Route::resource('participantes', 'App\Http\Controllers\Admin\ParticipanteController')->names('admin.participantes');
Route::resource('referencias',ReferenciaController::class)->names('admin.referencias');
Route::resource('subcategorias',SubcategoriaController::class)->names('admin.subcategorias');
Route::get('subcategorias/listarsubcategorias/',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::resource('patrocinadores',PatrocinadorController::class)->names('admin.patrocinadores');
Route::resource('ponentes',PonenteController::class)->names('admin.ponentes');
//Route::post('subcategorias/listarsubcategorias',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::get('users/export/{evento_id}', [UserController::class, 'export'])->name('admin.user.export');

routes/user.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ParticipanteController;
use App\Http\Controllers\User\EventoController;
use App\Http\Controllers\User\PagoController;

Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::resource('participante', ParticipanteController::class)->names('user.participantes');
Route::resource('evento', EventoController::class)->names('user.eventos');
Route::resource('pago', PagoController::class)->names('user.pagos');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventoController;
use App\Http\Controllers\ParticipanteController;

Route::get('/', [EventoController::class,'index'])->name('eventos.index');
Route::get('Eventos/{evento}', [EventoController::class,'show'])->name('eventos.show');
Route::get('/premiacion', function () {
    return view ('premiacion');
})->name('premiacion');



Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

resources/views/admin/patrocinadores/create.blade.php
@extends('adminlte::page')
@section('title', 'Lista Patrocinadores')

@section('content_header')
    <br>
@stop

@section('content')
    @if(session('info'))
        <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
        </div>
    @endif
    <x-adminlte-card title="Crear patrocinador" theme="success" theme-mode="outline" body-class="bg-none" header-class="bg-light"  footer-class="bg-none border-top rounded border-light"
    icon="fas fa-lg fa-plus" >
    
    <form action="{{route('admin.patrocinadores.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="form-group col-md-6">
                <label for="">Nombre</label>
                <input class="form-control @error('nombre') is-invalid @enderror" type="text" name="nombre" id="nombre" value="{{ old('nombre') }}">
                @error('nombre')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group col-md-6">
                <label for="">Descripción</label>
                <input class="form-control @error('descripcion') is-invalid @enderror" type="text" name="descripcion" id="descripcion" value="{{ old('descripcion') }}">
                @error('descripcion')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="">Pagina Web</label>
                <input class="form-control @error('pagina_web') is-invalid @enderror" type="text" name="pagina_web" id="pagina_web" value="{{ old('pagina_web') }}">
                @error('pagina_web')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group col-md-3 align-items-center">
                <div class="row">
                    <div class="form-group col-md-10">
                        <label for="">Logo :</label>
                    <input class="form-control-file" type="file" name="logo" id="logo">
                    <p class="text-danger">*Las imagenes deben ser en formato PNG, sin fondo y en un tamaño de 400 * 400 pixeles</p>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div class="image-wrapper">
                                    <img class="img img-rounded" id="picture" src="http://www.utcancun.edu.mx/wp-content/uploads/2016/06/Instalaciones-Deportivas-UT-Soccer-Americano.jpg" height="200px" width="200px" alt="">
                            </div> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <label for="">Facebook</label>
            </div>
            <div class="col-md-5 form-group">
                <div class="col-auto">
                    <label class="sr-only" for="inlineFormInputGroup">Username</label>
                    <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">www.facebook.com/</div>
                    </div>
                    <input type="text" class="form-control" id="facebook" name="facebook" placeholder="Username">
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <label for="">Instagram</label>
            </div>
            <div class="col-md-5 form-group"> 
                
                <div class="col-auto">
                    <label class="sr-only" for="inlineFormInputGroup">Username</label>
                    <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">@</div>
                    </div>
                    <input type="text" class="form-control" id="instagram" name="instagram" placeholder="Username">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <label for="">Tik Tok</label>
            </div>
            <div class="col-md-5 form-group">
                <div class="col-auto">
                    <label class="sr-only" for="inlineFormInputGroup">Username</label>
                    <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">@</div>
                    </div>
                    <input type="text" class="form-control" id="tiktok" name="tiktok" placeholder="Username">
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <label for="">X</label>
            </div>
            <div class="col-md-5 form-group">
            
                <div class="col-auto">
                    <label class="sr-only" for="inlineFormInputGroup">Username</label>
                    <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text"> https://x.com/</div>
                    </div>
                    <input type="text" class="form-control" id="x" name="x" placeholder="Username">
                    </div>
                </div>
                
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-success btn-lg">Guardar</button>
            </div>
        </div>
    </form>

    </x-adminlte-card>  

@stop
@section('js')
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
<script src="{{asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js')}}"></script>
<script>
    //imagen del formulario
    document.getElementById("logo").addEventListener('change',cambiarImagen);
    function cambiarImagen(event){
        var file= event.target.files[0];
        var reader = new FileReader();
        reader.onload = (event) => {
            document.getElementById("picture").setAttribute('src', event.target.result);
        };
        reader.readAsDataURL(file);
    }
</script>
@stop

resources/views/admin/patrocinadores/edit.blade.php
@extends('adminlte::page')
@section('title', 'Lista Patrocinadores')

@section('content_header')
    <br>
@stop

@section('content')
    @if(session('info'))
        <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
        </div>
    @endif
    <x-adminlte-card title="Crear patrocinador" theme="success" theme-mode="outline" body-class="bg-none" header-class="bg-light"  footer-class="bg-none border-top rounded border-light"
    icon="fas fa-lg fa-plus" >
    <form action="{{route('admin.patrocinadores.update', $patrocinadore->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="form-group col-md-6">
                <label for="">Nombre</label>
                <input class="form-control @error('nombre') is-invalid @enderror" type="text" name="nombre" id="nombre" value="{{$patrocinadore->nombre}}" placeholder="prueba">
                @error('nombre')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group col-md-6">
                <label for="">Descripción</label>
                <input class="form-control @error('descripcion') is-invalid @enderror" type="text" name="descripcion" id="descripcion" value="{{$patrocinadore->descripcion}}">
                @error('descripcion')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="">Pagina Web</label>
                <input class="form-control @error('pagina_web') is-invalid @enderror" type="text" name="pagina_web" id="pagina_web" value="{{ $patrocinadore->pagina_web }}">
                @error('pagina_web')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="form-group col-md-3 align-items-center">
                <div class="row">
                    <div class="form-group col-md-10">
                        <label for="">Logo :</label>
                    <input class="form-control-file" type="file" name="logo" id="logo" placeholder="logo">
                    <p class="text-danger">*Las imagenes deben ser en formato PNG, sin fondo y en un tamaño de 400 * 400 pixeles</p>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <div class="image-wrapper">
                                    <img class="img img-rounded" id="picture" src="@if($patrocinadore->image){{Storage::url($patrocinadore->image->url)}} @else {{Storage::url('patrocinadores/empty.png')}} @endif" height="200px" width="200px" alt="">
                            </div> 
                        </div>
                    </div>
                </div>    
            </div>
        </div>
        <div class="row">
        @foreach (json_decode($patrocinadore->redes) as $item=>$data)
        <div class="col-md-1">
            <label for="">{{$item}}</label>
        </div>
        <div class="col-md-5 form-group">
            <div class="col-auto">
                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <div class="input-group-text">www.{{$item}}.com/</div>
                </div>
                <input type="text" class="form-control" id="{{$item}}" name="{{$item}}" value="{{$data}}">
                </div>
            </div>
        </div>
        @endforeach
        </div>  
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{{route('admin.patrocinadores.index')}}" class="btn btn-danger btn-lg">Regresar</a>
                <button type="submit" class="btn btn-success btn-lg">Actualizar</button>
            </div>
        </div>
    </form>

    </x-adminlte-card>  

@stop
@section('js')
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
<script src="{{asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js')}}"></script>
<script>
    //imagen del formulario
    document.getElementById("logo").addEventListener('change',cambiarImagen);
    function cambiarImagen(event){
        var file= event.target.files[0];
        var reader = new FileReader();
        reader.onload = (event) => {
            document.getElementById("picture").setAttribute('src', event.target.result);
        };
        reader.readAsDataURL(file);
    }
</script>
@stop

resources/views/admin/patrocinadores/index.blade.php
@extends('adminlte::page')
@section('title', 'Lista Patrocinadores')

@section('content_header')
    <br>
@stop

@section('content')
    @if(session('info'))
        <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
        </div>
    @endif
   
            @livewire('admin.patrocinadores-index') 

@stop