routes/admin.php
<?php

use App\Http\Controllers\Admin\PonenteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PagoController;
use App\Http\Controllers\Admin\EventoController;
use App\Http\Controllers\Admin\ReferenciaController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SubcategoriaController;
use App\Http\Controllers\Admin\PermisoController;
use App\Http\Controllers\Admin\PatrocinadorController;

Route::get('', [HomeController::class, 'index'])->middleware('can:admin.home')->name('admin.home');
Route::resource('users', UserController::class)->only(['index','edit','update','destroy'])->names('admin.users');
Route::resource('roles', RoleController::class)->names('admin.roles');
Route::resource('permisos', PermisoController::class)->names('admin.permisos');
Route::resource('categorias',CategoriaController::class)->names('admin.categorias');
Route::resource('pagos',PagoController::class)->names('admin.pagos');
Route::get('pagos/aprobarpago/{pago}', [PagoController::class, 'aprobarpago'])->name('admin.pagos.aprobarpago');
Route::get('pagos/declinarpago/{pago}', [PagoController::class, 'declinarpago'])->name('admin.pagos.declinarpago');
Route::resource('eventos',EventoController::class)->names('admin.eventos');
Route::get('eventos/asistencia/{evento}', [EventoController::class, 'asistencia'])->name('admin.eventos.asistencia');
Route::get('eventos/lista/{evento}', [EventoController::class, 'lista'])->name('admin.eventos.lista');
Route::get('/admin/eventos/{id}/eventopago', [EventoController::class, 'eventopago'])->name('admin.eventos.eventopago');
Route::resource('participantes', 'App\Http\Controllers\Admin\ParticipanteController')->names('admin.participantes');
Route::resource('referencias',ReferenciaController::class)->names('admin.referencias');
Route::resource('subcategorias',SubcategoriaController::class)->names('admin.subcategorias');
Route::get('subcategorias/listarsubcategorias/',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::resource('patrocinadores',PatrocinadorController::class)->names('admin.patrocinadores');
Route::resource('ponentes',PonenteController::class)->names('admin.ponentes');
//Route::post('subcategorias/listarsubcategorias',[SubcategoriaController::class,'listarsubcategorias'])->name('admin.subcategorias.listarsubcategorias');
Route::get('users/export/{evento_id}', [UserController::class, 'export'])->name('admin.user.export');

routes/user.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\ParticipanteController;
use App\Http\Controllers\User\EventoController;
use App\Http\Controllers\User\PagoController;

Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::get('', [HomeController::class, 'index'])->name('user.home');
Route::resource('participante', ParticipanteController::class)->names('user.participantes');
Route::resource('evento', EventoController::class)->names('user.eventos');
Route::resource('pago', PagoController::class)->names('user.pagos');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventoController;
use App\Http\Controllers\ParticipanteController;

Route::get('/', [EventoController::class,'index'])->name('eventos.index');
Route::get('Eventos/{evento}', [EventoController::class,'show'])->name('eventos.show');
Route::get('/premiacion', function () {
    return view ('premiacion');
})->name('premiacion');



Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Evento.php
<?php

namespace App\Models;

use Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Evento extends Model
{
    use HasFactory;
    protected $guarded =['id', 'created_at', 'updated_at'];
    public function user(){
        return $this->belongsTo('App\Models\User');
    }
    public function categoria(){
        return $this->belongsTo(Categoria::class);
    }
    public function image(){
        return $this->morphOne(Image::class, 'imageable');
    }
    public function archivo(){
        return $this->morphOne(Archivo::class, 'archivable');
    }
    public function pagos(){
        return $this->belongsToMany(Pago::class)->withTimestamps();
    }
    public function participantes(){
        return $this->belongsToMany(Participante::class)->withTimestamps();
    }
   public function setevento(){
        return $this->hasOne(Setevento::class);
    }
    public function correo(){
        return $this->hasOne(Correo::class);
    }
    public function referencias(){
        return $this->morphToMany(Referencia::class,'referenciable');
    }
    public function patrocinadores(){
        return $this->belongsToMany(Patrocinador::class)->withTimestamps();
    }
    public function ponente(){
        return $this->belongsToMany(Ponente::class)->withTimestamps();
    }
    public function subcategorias(){
        return $this->belongsToMany(Subcategoria::class)->withTimestamps();
    }
    protected function informacion(): Attribute
    {
        return Attribute::make(
            set: fn(string $value) => $this->makeInformacionContent($value),
        );  
    }
    public function makeInformacionContent($content)
    {
        $dom = new \DomDocument();
        $dom->loadHtml($content, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        $imageFile = $dom->getElementsByTagName('img');  
            foreach($imageFile as $item => $image){
                $data = $image->getAttribute('src');
                list($type, $data) = explode(';', $data);
                list(, $data)      = explode(',', $data);
                $imgeData = base64_decode($data);
                $image_name= "/uploads/" . time().$item.'.png';
                $path = public_path() . $image_name;
                file_put_contents($path, $imgeData);
                     
                $image->removeAttribute('src');
                $image->setAttribute('src', $image_name);
            }
            return $dom->saveHTML();
    }
}

app/Http/Controllers/Admin/EventoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Patrocinador;
use Illuminate\Http\Request;
use App\Models\Evento;
use App\Models\Ponente;
use App\Models\Categoria;
use App\Http\Requests\EventoRequest;
use App\Models\Participante;
use App\Models\Setevento;
use App\Models\Referencia;
use App\Models\User;
use App\Models\Pago;
use App\Models\Subcategoria;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;


class EventoController extends Controller
{

    public function __construct()
    {
        
        $this->middleware('can:admin.eventos.index')->only('index');
        $this->middleware('can:admin.eventos.edit')->only('edit','update');
        $this->middleware('can:admin.eventos.create')->only('create','store');
    }
    public function index()
    {
        return view('admin.eventos.index');
    }
   
    public function create()
    {
        $patrocinadores= Patrocinador::with('image')->get();
        $ponentes = Ponente::with('image')->get();
            return view('admin.eventos.create',compact('patrocinadores','ponentes',));
    }
    
    public function store(EventoRequest $request)
    {
        //dd($request);
        $evento = new Evento();   
        DB::beginTransaction();      
            $evento = Evento::create($request->all());
            //return $evento;
            Setevento::create([
            'detalle'=>$request->detalle,
            'requisitos'=>$request->requisitos,
            'video'=>$request->video,   
            'localidad'=>$request->localidad,
            'inscritos' => 0,
            'capacidad' => $request->capacidad,       
            'fechaevento'=>$request->fechaevento,
            'horaInicio'=>$request->horaInicio,
            'iniciainscripcion'=>$request->iniciainscripcion,
            'terminainscripcion'=>$request->terminainscripcion,
            'evento_id'=>$evento->id
            ]);
                    
        if($request->file('image')){
          $url = Storage::put('public/eventos', $request->file('image'));
          $task = $evento->image()->create([
            'url' => $url
            ]);
        }
        if($request->file('archivo')){
            $url = Storage::put('public/eventos', $request->file('archivo'));
            $task = $evento->archivo()->create([
              'url' => $url
              ]);
          }
        $evento->subcategorias()->attach($request->subcategoria);
        $evento->patrocinadores()->attach($request->patrocinador);
        $evento->ponente()->attach($request->ponente);
        DB::commit();
        return redirect()->route('admin.eventos.index',$evento)->with('info','evento creado con éxito');
    }

    //**Esta accion nos mostrara los detalles del evento de la tabla seteventos**//
    public function show(Evento $evento)
    {    
        $similares = Evento::with('image','setevento','archivo')
        ->where('categoria_id',$evento->categoria_id) //misma categoria
        ->where('status',2)//activos
        ->where('id','!=',$evento->id)
        ->latest('id')//por id
        ->take(3)//solo 3
        ->get();
        return view('Eventos.show', compact('evento','similares'));
    }
    
    public function edit(Evento $evento)
    {
        //return $evento;
        $this->authorize('author', $evento);
        $categorias = $evento->categoria->pluck('nombre', 'id');// este nos dara id y nombre para pasarlo al select
        $subcategorias = Subcategoria::all();
        $patrocinadores= Patrocinador::with('image')->get();
        $ponentesall = Ponente::with('image')->get();
        $ponentes= $evento->ponente()->get(['ponente_id']);
        $setevento = $evento->setevento;
        //return $setevento;
        return view('admin.eventos.edit', compact('evento','setevento','categorias','subcategorias','patrocinadores','ponentes','ponentesall'));
    }  
    public function update(EventoRequest $request, Evento $evento)
    {
        //return $request->ponente;
        DB::beginTransaction();   
        $this->authorize('author', $evento);
        $evento->update($request->all());
        $evento->setevento->update([
            'detalle'=>$request->detalle,
            'requisitos'=>$request->requisitos,
            'video'=>$request->video,   
            'localidad'=>$request->localidad,
            //'inscritos' => 0,
            'capacidad' => $request->capacidad,      
            'fechaevento'=>$request->fechaevento,
            'horaInicio'=>$request->horaInicio,
            'iniciainscripcion'=>$request->iniciainscripcion,
            'terminainscripcion'=>$request->terminainscripcion,
            'evento_id'=>$evento->id
        ]);     
        
        if($request->file('image')){
            $url = Storage::put('public/eventos', $request->file('image'));

            if($evento->image){
            Storage::delete($evento->image->url);
            $evento->image->update([
                'url' => $url
            ]);
            }else{
                $evento->image()->create([
                'url' => $url
                ]);
            }
        }
        if($request->file('archivo')){
            $url = Storage::put('public/eventos', $request->file('archivo'));

            if($evento->archivo){
            Storage::delete($evento->archivo->url);
            $evento->archivo->update([
                'url' => $url
            ]);
            }else{
                $evento->archivo()->create([
                'url' => $url
                ]);
            }
        }
        $evento->subcategorias()->sync($request->subcategoria);
        //$evento->referencias()->sync($request->referencias);
        $evento->patrocinadores()->sync($request->patrocinador);
        $evento->ponente()->sync($request->ponente);
        DB::commit();
        return redirect()->route('admin.eventos.index', $evento)->with('info','El evento se actualizó con éxito');
    }

    public function lista(Evento $evento){
       //return "prueba";
        $pagos = $evento->pagos()->get();
        $deta = Evento::with('participantes','pagos','image')->find($evento->id);
       //return $deta;
        return view('admin.eventos.lista', compact('evento','pagos','deta'));
    }
    public function eventopago(Evento $evento)
    {
        return $evento->id;
    }
    public function asistencia(Evento $evento){
        $participantes = Evento::with('participantes')->get();
    
        //dd( $participantes);
        return view('admin.eventos.asistencia', compact('participantes','evento'));
    }
    public function destroy(Evento $evento)
    {
        $this->authorize('author', $evento);
        $evento->Setevento->delete();
        if($evento->image){
            Storage::delete($evento->image->url);   
        };
        if($evento->archivo){
        Storage::delete($evento->archivo->url);
        }
        $evento->delete();
        return redirect()->route('admin.eventos.index')->with('info','El evento se eliminó con éxito');
    }
}

app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Evento;
use App\Models\Participante;

class EventoController extends Controller
{
    public function index(){
        $eventos = Evento::with(['image','setevento'])
        ->where('status',2)
        ->latest('id')
        ->paginate(7);
        //return $eventos;
        return view('Eventos.index', compact('eventos'));
        
    }
    public function show(Evento $evento){
        $this->authorize('published',$evento);
        $similares = Evento::with('image','setevento','archivo','participantes:id','ponente')
        ->where('categoria_id',$evento->categoria_id) //misma categoria
        ->where('status',2)//activos
        ->where('id','!=',$evento->id)
        ->latest('id')//por id
        ->take(4)//solo 3
        ->get();
        //$patrocinadores=$evento->patrocinadores();
        //$ponentes= $evento->ponente;
        //dd ($ponentes);
        return view('Eventos.show', compact('evento','similares'));
    }
}

app/Http/Controllers/User/EventoController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Evento;
use App\Models\Participante;
use App\Models\Referencia;
use Illuminate\Support\Facades\Auth;
use App\Models\Pago;
use Illuminate\Support\Carbon;
//use App\Mail\RegistroEventos;
//use Illuminate\Support\Facades\Mail;
use DateTime;

class EventoController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:user.eventos.index')->only('index');
        $this->middleware('can:user.eventos.edit')->only('edit','update');
       // $this->middleware('can:user.eventos.create')->only('create','store');
    }
    
    public function index()
    {
        return view('user.eventos.index');
    }
    
    public function show(Request $request, Evento $evento)
    {
        return view('user.eventos.show');
    }

    
    public function edit( Evento $evento )
    {     
        $participante= Participante::find(auth()->user()->id);
        $tipo= Referencia::find($evento);
        return view('user.eventos.edit', compact('evento','participante','tipo'));
    }

    /**request trae el participante**/
    /**$evento trae los datos del evento**/
    public function update(Request $request, Evento  $evento)
    {   
       
        //return $request;
        $participante= Participante::find($request->participante);
        $inscritos= $evento->setevento->inscritos;
        $capacidad= $evento->setevento->capacidad;
        $fechaInicio= new DateTime($evento->setevento->fechaInicio);
        $fechaFin= new DateTime($evento->setevento->fechaFin);
        $today= Carbon::now();
        //return $today;
       
            if($inscritos < $capacidad){
                $participante->update($request->all());
                $participante->subcategorias()->attach($request->subcategoria);
                $evento->setevento->increment('inscritos');
                $vencimiento = (new DateTime('+10 days'))->format('Y-m-d');
                $pago= Pago::create([
                    'referencia' =>$request->referencia,
                    'monto'=>$request->monto,
                    'fechavencimiento'=> $vencimiento,
                    'tipo' => 1,
                    'estatuspago'=> 3,
                    'participante_id' => $request->participante ]);
                $evento->pagos()->attach($pago);
            }else{
                return back()->with('fail','El evento esta lleno o no admite mas inscritos.');
            }
        return redirect()->route('user.eventos.edit',$evento)->with('done', 'Se inscribió correctamente al evento');
    }
    public function qrcode(Request $request)
    {
        //$qrParticipante= QrCode::size(300)->generate('https://techvblogs.com/blog/generate-qr-code-laravel-9');
        //return view() 
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**Desde aqui inicia la plantilla **/
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/eventos/asistencia.blade.php
@extends('adminlte::page')
@section('title', 'Asistencia a evento')
@section('content_header')
    <h1>Capturar asistencia a evento : {{$evento->nombre}}</h1>
@stop
@section('content')
    @livewire('admin.asistencia')
@stop
@section('js')
<script src="https://unpkg.com/html5-qrcode"></script>
<script>
    //console.log('prueba');
    var resultContainer = document.getElementById('qr-reader-results');
    var lastResult, countResults = 0;
    const eventoId = {!! json_encode($evento['id']) !!};
    //console.log(evento['id']);
    function onScanSuccess(decodedText, decodedResult) {
        if (decodedText !== lastResult) {
            ++countResults;
            lastResult = decodedText;
            console.log(`Scan result: ${decodedText}`, decodedResult);
            //Livewire.emit("asistenciaP",['idparticipante' => decodedResult,'evento'=> eventoId]);
            Livewire.emit('asistenciaP', [decodedText,eventoId]);
            //var arg = {'key': key, 'idEvento': evento,'idparticipante' =decodedResult};           
            //if (result.value) {
              //  Livewire.emit("asistenciaP", arg);
            //}
            //resultContainer.innerHTML += `<p>[${countResults}] - ${decodedText}</p>`;
            //Livewire.emit('asistenciaP',[{'idparticipante' =decodedResult,'evento'=> evento}]);
            

            resultContainer.innerHTML += 'vamo pue' ;
            /*Livewire.on('asistenciaP',(){
                //resultContainer.innerHTML += 'vamo pue' ;
                alert('Asistencia aprobada');
            })*/
            
            
        }
    }
    var html5QrcodeScanner = new Html5QrcodeScanner(
        "qr-reader", { fps: 10, qrbox: 250 });
        html5QrcodeScanner.render(onScanSuccess);
        
</script>
@endsection

resources/views/admin/eventos/create.blade.php
@extends('adminlte::page')
@section('title', 'Eventos UT')

@section('content_header')
    <h1 class="text-center">Crear nuevo evento</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('admin.eventos.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                @include('admin.eventos.partials.form')
                <div class="row justify-center ">
                    <button type="submit" class="btn btn-success btn-lg btn-block" >Guardar</button>
                </div>
            </form>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <style>
    .image-wrapper{
        position :relative;
        padding-bottom: 56.25%;
    }
    .image-wrapper img{
        position: absolute;
        object-fit: cover;
        width: 100%;
        height: 100%;
    }
</style>
@stop

@section('js')

        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script src="{{asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js')}}"></script>


<script>
     $(document).ready( function() {
    $("#nombre").stringToSlug({
        setEvents: 'keyup keydown blur',
        getPut: '#slug',
        space: '-'
        });
    });
    $('#informacion').summernote({
        placeholder: 'Aqui va toda la informacion importante del evento',
        tabsize: 10,
        height: 200
      });
    //imagen del formulario
    //document.getElementById("image").addEventListener('change',cambiarImagen);
    $("#image").on('change', function() {
                const [file] = this.files
                let pictureResult=document.getElementById("picture");
                let errorLabel= document.getElementById("imageerror");
                if (file) {
                    const img = new Image();
                    img.onload = function() {
                        
                        if(this.width){
                            let cumple= false;
                            if(this.height/this.width < .68 ){
                                if(this.height/this.width > .55)
                                {
                                    pictureResult.setAttribute('src', img.src);
                                    errorLabel.innerHTML = "";
                                    //console.log('cumple con 16-9');    
                                }else{
                                        //console.log('jsnjsnd');
                                        errorLabel.innerHTML = "<p class='text-danger'>La imagen debe ser en formato 16:9 por ejemplo: 1280*850px /1024*576px</p>";
                                }
                            }else{
                                //console.log('la imagen es muy cuadrada');
                                errorLabel.innerHTML = "<p class='text-danger'>La imagen debe ser en formato 16:9 por ejemplo: 1280*850px /1024*576px</p>";
                            }
                        }
                       
                    }
                    img.src = URL.createObjectURL(file);
                }
});
</script>
@stop

resources/views/admin/eventos/index.blade.php
@extends('adminlte::page')
@section('title', 'Eventos UT')

@section('content_header')

<!--a  class="btn btn-outline-success btn-sm float-right"href="{{route('admin.eventos.create')}}">Nuevo Evento</a-->
    <h1>Todos los Eventos</h1>
@stop

@section('content')

@if(session('info'))
    <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
    </div>
@endif
    @livewire('admin.evento-index')
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/eventos/lista.blade.php
@extends('adminlte::page')
@section('title', 'Lista Pagos')

@section('content_header')  
    <h1>Lista de pagos del evento {{$evento->nombre}}</h1>
@stop

@section('content')
@if(session('info'))
    <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
    </div>
@endif
    <div class="card">
        <div class="card-body">
            <table class="table table-stripped">
               
               <thead>
                   <tr>
                       <th>Participante</th>
                       <th>Inscritos</th>
                   </tr>
                </thead> 
                <tbody>
                    <tr>
                    @foreach ($deta->pagos as $pagos)
                      
                    @endforeach
                </tr>
                   
                    <tr>
                   
                </tr> 
                
                   
                   
                   <tr>
                    <td></td>
                    <td>
                       
                    </tr>
                  
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin/eventos/show.blade.php
@extends('adminlte::page')
@section('title', 'Eventos UT')

@section('content_header')
    <h1>detalles evento</h1>
@stop
@section('content')
<div class="card">
    <div class="card-body">
        <x-app-layout>
            <!--div class="text-center pt-16 md:pt-32">
                  <p class="text-sm md:text-base text-green-500 font-bold"> <span class="text-gray-900">/</span> GETTING STARTED</p-->
                  <h1 class="font-bold break-normal text-2xl md:text-3xl"></h1>
              </div-->
              <!--IMAGEN-->
              <div class="container w-full max-w-6xl mx-auto bg-white bg-cover mt-1 rounded" style="background-image:url('@if($evento->image){{Storage::url($evento->image->url)}}@else http://www.utcancun.edu.mx/wp-content/uploads/2016/06/Instalaciones-Deportivas-UT-Soccer-Americano.jpg @endif'); height: 75vh;"></div>
              <!--CONTENEDOR-->
              <div class="container max-w-5xl mx-auto -mt-5 opacity-90">
                  <div class="mx-0 sm:mx-6">
                      <div class="bg-white w-full p-8 md:p-18 text-xl md:text-1xl text-gray-800 leading-normal">
                          <!--CONTENIDO-->
                          <p class="text-2xl md:text-2xl mb-1 ">
                              {{$evento->nombre}}
                          </p>
                          <p class="py-1 text-justify ">{!!$evento->informacion!!}</p>				
                          <ol>
                              <li class="py-3">Lugar : {{$evento->setevento->localidad}}</li>
                              <li class="py-3">Locación : {{$evento->setevento->detalle}}</li>
                              <li class="py-3">Periodo de inscripción : Del {{strftime($evento->setevento->iniciainscripcion)}} al {{$evento->setevento->terminainscripcion}}</li>
                              <li class="py-3">Fecha del evento :{{$evento->setevento->fechaevento}}</li>
                          </ol>								
                          <!--BOTON CONVOCATORIA-->
                          <div class="container font-sans bg-white rounded mt-2 p-4 text-center">
                              <div class="w-full text-center pt-4">
                                  <div class="max-w-sm mx-auto p-1 pr-0 flex flex-wrap items-center">
                                      
                                  </div>
                              </div>
                          </div>
                      </div>              
                      
                  </div>
              
          
              </div>
          </x-app-layout>
        
       
    </div>

</div>
    
@stop